### ISSUE TITLE
edgesTrain parfor issue and issues following the solution

### ISSUE THREAD

**Issue by tteresi7** [pdollar/edges#10]
> ??? Error: File: edgesTrain.m Line: 157 Column: 18
> The variable eBins in a parfor cannot be classified.
>  See Parallel for Loops in MATLAB, "Overview".

I am getting this error while trying to run edgesDemo.  It looks like the error stems from using two different indices within the loop.  The variables need sliced to operate correctly.

Switching to something like this:

`parfor i=1:nTrees*nNodes
    if(model.child(i) || model.nSegs(i)==1), continue;end %#ok<PFBNS>
    E=gradientMag(single(model.segs(:,:,i)))>.01; E0=0;
    sliceBins = eBins{i}; sliceBnds = eBnds(i);
    for j=1:nBnds, %eBins{i,j}=uint16(find(E & ~E0)'-1); E0=E;
        %eBnds(i,j)=length(eBins{i,j}); E=convTri(single(E),1)>.01; end
        sliceBins{j} = unit16(find(E&~E0)'-1); E0=E;
        sliceBnds(j)=length(sliceBins{j}); E=convTri(single(E),1)>0.1; end`

Solves the issue.

EDIT:  Solved the issue that results from the solution of this issue.  I needed to add the toolbox path back in because it got removed.

**Comment by pdollar** [comment]
I just tried running the code and it works fine. Are you using a really old version of Matlab? Anyway, worst case just remove parfor and run as regular for loop.

**Comment by Addhi86** [comment]
@tteresi7 Have you used the Edge box with different dataset?
