### ISSUE TITLE
Where to download additional model (D/RGBD)

### ISSUE THREAD

**Issue by claudehang** [pdollar/edges#15]
I've seen in README there are additional models online, but I can't find them on the Internet. Would you give a specific link where I can download them? Many thanks!

**Comment by rpandey4** [comment]
Hello @pdollar  I am also very interested if you provide the model from NYU Depth dataset. TIA

**Comment by Azpril45** [comment]
Hello @claudehang @gizmowiki .
I got the same problem with you guys. I was wondering If you have already got the model, can you tell me where to get them?
Also it will be appreciate if you @pdollar can provide these models.
Thank you.

Sincerely yours
April

**Comment by pdollar** [comment]
The models can be found off my personal page: https://pdollar.github.io/research.html (scroll down to https://pdollar.github.io/research.html#BoundaryFeatureLearning --> Code). Thanks and sorry those were hard to find!

**Comment by alt01** [comment]
Whe I substitute "modelBsds.mat" by "modelNyuRgbd.mat", I have the following errors:

Error using edgesChns (line 38)
Assertion failed.

Error in edgesDetect (line 55)
  [chnsReg,chnsSim] = edgesChns( I, opts );

Error in bordes>listbox1_Callback (line 121)
E=edgesDetect(I,model);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in bordes (line 52)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)bordes('listbox1_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

Were you able to implement the NyuRgbd dataset?
