### ISSUE TITLE
model.opts.multiscale and model.opts.sharpen

### ISSUE THREAD

**Issue by howtobeahacker** [pdollar/edges#2]
Hi @pdollar,
What is the meaning of **multiscale** and **sharpen** option? According to your documents, I set 
```
model.opts.multiscale=1; model.opts.sharpen=0;
```
The running time is faster and the accuracy is better. Multiscale is **multiscale** bounding box, isn't it? I am not sure clear about **sharpen** option.

**Comment by pdollar** [comment]
Please see the edge detection documentation (https://github.com/pdollar/edges/blob/master/edgesTrain.m) and associated papers for additional details (http://arxiv.org/abs/1406.5549).
