### ISSUE TITLE
performance on PASCAL VOC 07 dataset

### ISSUE THREAD

**Issue by akiradesu** [pdollar/edges#3]
I evaluated proposals generated using `edgeBoxes.m` on PASCAL VOC 2007 test set and achieved a maximum recall of 76% with IoU = 0.7, which is far lower than 87% reported in your paper. I used default values for all parameters. Any suggestions?

**Comment by pdollar** [comment]
I just rand the code out of the box and got ~87% recall. 

Please run edgeBoxesDemo.m
(1) In the last cell, if you run "boxesEval('data',data,'names',nm,'thrs',.7,'show',2);" you'll get the first attached plot below which shows recall is ~87%.
(2) If you run "boxesEval('data',data,'names',nm,'thrs',.5:.05:1,'cnts',1000,'show',3);" recall at IoU=.7 is about 80%. But this is with 1000 boxes, the 87% recall in the paper is w 5000 boxes. So if you rerun that snippet w cnts=5000 then you indeed get 87% back. This is the second plot attached

Note that Jan Hosang verified the results independently using his own evaluation code and running the edge boxes code himself (https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/object-recognition-and-scene-understanding/how-good-are-detection-proposals-really/).

I hope this clarifies your questions (if not feel free to reach out again, but first, please spend some time going through the code and results in more detail)

![a](https://cloud.githubusercontent.com/assets/699682/10748623/6e5dff98-7c1f-11e5-8766-466da7e3e135.jpg)


![b](https://cloud.githubusercontent.com/assets/699682/10748708/1eefdbb0-7c20-11e5-9f9c-fdcddab7d750.jpg)

**Comment by Addhi86** [comment]
@akiradesu Can you please tell me then I run the edgeBoxesDemo, I got an error of Groundtruth-val.mat not found. How can i add that?
