### ISSUE TITLE
Error using edgesChns (line 41) Assertion failed

### ISSUE THREAD

**Issue by petteriTeikari** [pdollar/edges#4]
Hi @pdollar 

I got the following error when using your `edges_demo.m`

```matlab
Error using edgesChns (line 41)
Assertion failed.

Error in edgesDetect (line 55)
  [chnsReg,chnsSim] = edgesChns( I, opts );

Error in edgeBoxesIedgeBoxesImg (line 92)
model.opts.nms=0; [E,O]=edgesDetect(I,model);

Error in edgeBoxes (line 82)
if(~iscell(I)), bbs=edgeBoxesImg(I,model,o); else n=length(I);

Error in edgeBoxesDemo (line 16)
tic, bbs=edgeBoxes(I,model,opts); toc
```

Which was fixed by converting the grayscale `pepper.png` into a RGB image. Do the images always have to be converted to RGB or could the code be used for grayscale images as well?

**Comment by pdollar** [comment]
Yes, the method requires RGB images. The simple fix for grayscale images is to trivially convert to a color image RGB=cat(3,I,I,I). Alternatively, one could retrain for grayscale images (and slightly tweak the code) but it was never a priority for me to do so. Thanks!
