### ISSUE TITLE
Extension to 3D?

### ISSUE THREAD

**Issue by petteriTeikari** [pdollar/edges#5]
Hi Piotr,

Have you thought of extending the future version to classifying edges in 3D? I have been using now your code on a slice-by-slice basis for our 2-PM microscope stacks trained with our own ground truths, and the results are quite good :) I would assume that the results would be even better if full 3D context would be taken into account?

Petteri

**Comment by pdollar** [comment]
Hi Petteri -- Seems like a natural extension. I have not seen this before but our older work on (non-structured) edge detection did have an extension to 3D (see a paper title "Brain Anatomical Structure Segmentation..." in TMI 2008). For the more modern structured edges I have not seen this done. I expect it would work quite, better than 2D edges applied on independent slices, well it but might require a bit more training data than the 2D case.

**Comment by petteriTeikari** [comment]
Thanks for the reply Piotr,

I have to play then with your code at some point when I have the time, and see if the results improve :)
