### ISSUE TITLE
Object specific edges?

### ISSUE THREAD

**Issue by ultrai** [pdollar/edges#6]
Hi Piotr,
Thanks! for the great toolbox. 
While training, object specific edges (t=gt.segmentation) are provided but model.segs (tree nodes) stores sparse patches not reflecting labels. So only edge probability plane (all edges) is estimated. Does the toolbox accommodate to store object specific edges/labels. 

Thanks,
SPK Karri

**Comment by pdollar** [comment]
You could potentially train the model with object specific edges, but we have not done so.
